package org.atomhopper.dynamodb.model;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.atomhopper.dynamodb.constant.DynamoDBConstant;

import java.util.*;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName = DynamoDBConstant.ENTRIES)
public class PersistedEntry {

    @DynamoDBHashKey(attributeName = DynamoDBConstant.ENTRY_ID)
    private String entryId;
    @DynamoDBIndexRangeKey(attributeName = DynamoDBConstant.FEED,
            localSecondaryIndexName = "entryId-feed-index")
    @DynamoDBIndexHashKey(globalSecondaryIndexName="global-feed-index", attributeName = DynamoDBConstant.FEED)
    private String feed;
    private String entryBody;
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private String creationDate;
    @DynamoDBRangeKey(attributeName = DynamoDBConstant.DATE_LAST_UPDATED)
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
    private String dateLastUpdated;
    private List<String> categories;
}
